export default {
  leftArrow: require('../assets/icons/leftArrow.png'),
  user: require('../assets/icons/user.png'),
  union: require('../assets/icons/union.png'),
  homeFilled: require('../assets/icons/homeFilled.png'),
  homeOutlined: require('../assets/icons/homeOutlined.png'),
  performanceFilled: require('../assets/icons/performanceFilled.png'),
  performanceOutlined: require('../assets/icons/performanceOutlined.png'),
  refuellingFilled: require('../assets/icons/refuellingFilled.png'),
  refuellingOutlined: require('../assets/icons/refuellingOutlined.png'),
  vehiclesFilled: require('../assets/icons/vehiclesFilled.png'),
  vehiclesOutlined: require('../assets/icons/vehiclesOutlined.png'),
  down: require('../assets/icons/down.png'),
  leftArrow: require('../assets/icons/leftArrow.png'),
  cameraFilled: require("../assets/icons/cameraFilled.png"),
  delete: require("../assets/icons/delete.png"),
  rightSmallArrow: require("../assets/icons/rightSmallArrow.png"),
  calender: require("../assets/icons/calender.png"),
  delete2: require("../assets/icons/delete2.png"),
};